---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      initContainers:
        - name: wait-longhorn-manager
          image: longhornio/longhorn-manager:v1.1.0-arm64
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: longhorn-driver-deployer
          image: longhornio/longhorn-manager:v1.1.0-arm64
          imagePullPolicy: IfNotPresent
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - longhornio/longhorn-manager:v1.1.0-arm64
          - --manager-url
          - http://longhorn-backend:9500/v1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          # Manually set root directory for csi
          #- name: KUBELET_ROOT_DIR
          #  value: /var/lib/rancher/k3s/agent/kubelet
          - name: CSI_ATTACHER_IMAGE
            value: longhornio/csi-attacher:v2.2.1-lh1-arm64
          - name: CSI_PROVISIONER_IMAGE
            value: longhornio/csi-provisioner:v1.6.0-lh1-arm64
          - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
            value: longhornio/csi-node-driver-registrar:v1.2.0-lh1-arm64
          - name: CSI_RESIZER_IMAGE
            value: longhornio/csi-resizer:v0.5.1-lh1-arm64
          - name: CSI_SNAPSHOTTER_IMAGE
            value: longhornio/csi-snapshotter:v2.1.1-lh1-arm64
          - name: CSI_ATTACHER_REPLICA_COUNT
            value: "1"
          - name: CSI_PROVISIONER_REPLICA_COUNT
            value: "1"
          - name: CSI_RESIZER_REPLICA_COUNT
            value: "1"
          - name: CSI_SNAPSHOTTER_REPLICA_COUNT
            value: "1"
      serviceAccountName: longhorn-service-account
      securityContext:
        runAsUser: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-ui
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-ui
  template:
    metadata:
      labels:
        app: longhorn-ui
    spec:
      containers:
      - name: longhorn-ui
        image: longhornio/longhorn-ui:v1.1.0-arm64
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8000
          name: http
        env:
          - name: LONGHORN_MANAGER_IP
            value: "http://longhorn-backend:9500"
