{
 "title": "Kubernetes on Raspberry Pi",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{resource=\"memory\"})\n/\nsum by (node)(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{resource=\"cpu\"})\n/\nsum by (node)(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Load Average (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "proc" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{node}}" }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Succeeded Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{namespace!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods CPU Usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}