---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      name: loki
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.0.0
        args:
        - --config.file
        - /etc/loki/loki.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/loki
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: loki
