---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30100
