---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.22.0
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
          readOnly: true
        resources:
          requests:
            cpu: 300m
            memory: 350Mi
      volumes:
      - name: config
        configMap:
          name: prometheus
